### ISSUE TITLE
Bump to  v0.44.1

### ISSUE THREAD

**Issue by codingjoe** [metabase/metabase-buildpack#19]
@diogormendes, would you be so kind and bump the buildpack to the latest bug fix release, v0.44.0?
Thanks <3

**Comment by flamber** [comment]
Fixed by #20

**Comment by alxnddr** [comment]
@codingjoe I've just updated it

Closed by https://github.com/metabase/metabase-buildpack/pull/20

**Comment by francois2metz** [comment]
Hi! Could you also create the corresponding tag?

**Comment by alxnddr** [comment]
@francois2metz sorry for missing it, I've pushed the tag
