### ISSUE TITLE
missing update to 0.26.0 RC1

### ISSUE THREAD

**Issue by kritop** [metabase/metabase-buildpack#2]
are you going to update the buildpack like you did with previous RCs?

**Comment by salsakran** [comment]
RC1 is fairly fresh, we'll probably update it to RC2 or once we feel like things are stable. This buildpack is the default one that users who click "deploy" on http://www.metabase.com/start/heroku.html get, so we tend to be fairly conservative in what gets merged into master.

**Comment by kritop** [comment]
alright thanks, just wanted to make sure because the last time both RCs were released.

**Comment by ArtursO** [comment]
Doesn't look like Metabase 0.25.2 has been updated. Buildpack is still 0.25.1.

I had a general question - are you slowly phasing out support for Heroku? Out of curiosity and so I know whether to look at somewhere else to host Metabase.

**Comment by kritop** [comment]
@ArtursO its on the latest stable 0.25.2 see https://github.com/metabase/metabase-buildpack/commit/deeecb628bafbc8d4d39324866b60b7cb4dec87e

**Comment by ArtursO** [comment]
That's odd. I've followed all the instruction to upgrade Metabase on Heroku but I keep getting a "Everything-up-to-date" message in Terminal when I try to push the latest clone of Metabase (`git clone https://github.com/metabase/metabase-deploy.git`)

![image](https://user-images.githubusercontent.com/6081495/30387176-ba4c24c0-9879-11e7-8bc0-248180558078.png)

**Comment by kritop** [comment]
@ArtursO i had a similar issue, thought it was because i didnt use the force flag. but i got around it by just doing a local readme change, commiting that and then do a push. that will trigger surely an update.

**Comment by ArtursO** [comment]
This worked - thanks a lot @kritop !
